name: Marathon

on:
  workflow_dispatch:
    inputs:
      test_plan_type:
        description: "Select the test plan"
        required: true
        type: choice
        options:
          - Smoke
          - Regression
        default: Regression

env:
  PROJECT: 'SwiftRadio.xcodeproj'
  SCHEME: 'SwiftRadioUITests'
  DERIVED_DATA_PATH: 'DerivedData'
  TEST_RESULTS: './TestResults.xcresult'
  ALLURE_RESULTS: 'allure-results'
  SIMULATOR_VERSION: '18.0'
  SIMULATOR_NAME: 'iPhone 16'
  TEST_REGEXP: ".*"

jobs:
  build:
    name: Build
    runs-on: [macos-15]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Project
        id: build
        run: |
          set -o pipefail
          xcodebuild build-for-testing \
          -project ${{ env.PROJECT }} \
          -scheme ${{ env.SCHEME }} \
          -derivedDataPath ${{ env.DERIVED_DATA_PATH }} \
          -destination 'platform=iOS Simulator,name=${{ env.SIMULATOR_NAME }},OS=${{ env.SIMULATOR_VERSION }}' \
          CODE_SIGNING_ALLOWED='NO' \
          | xcbeautify --renderer github-actions
          
          mkdir TestData
          patterns=("*.xctest" "*.app" "*.xctestrun" "*.framework" "*.bundle")
          for pattern in "${patterns[@]}"; do 
            find "${{ env.DERIVED_DATA_PATH }}" -name "$pattern" -print | pax -rw -pe "TestData"; 
          done
          echo "artifacts_path=TestData/${{ env.DERIVED_DATA_PATH }}" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          path: ${{ steps.build.outputs.artifacts_path }}
          name: TestData
          retention-days: 30

  test:
    name: Run tests
    runs-on: [macos-15]
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: TestData
          path: ${{ env.DERIVED_DATA_PATH }}

      - name: Download Allure Parser of XCResults
        run: |
          curl -OL https://github.com/eroshenkoam/xcresults/releases/download/1.19.0/xcresults
          chmod +x xcresults

      - name: Install Allure
        run: brew install allure

      - name: Install Marathon
        run: |
          brew tap malinskiy/tap
          brew install malinskiy/tap/marathon

      - name: Run Ui Tests
        run: |
          pwd
          ls -la
          marathon -m marathon/Marathonfile
        continue-on-error: true