name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      manual:
        description: 'Run?'
        required: false
        type: boolean

jobs:
  build:
    name: Test
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ui Tests
        run: |
          xcodebuild test \
                    -scheme SwiftRadioUITests \
                    -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
                    -allowProvisioningUpdates