name: Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      manual:
        description: 'Run?'
        required: false
        type: boolean

jobs:
  build:
    name: Test
    runs-on: [macos-latest]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Ui Tests
        run: |
          xcodebuild test \
          -scheme SwiftRadioTests \
          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' 

#jobs:
#  build:
#    name: Test
#    runs-on: self-hosted
#
#    steps:
#      - name: Checkout repository
#        uses: actions/checkout@v3
#
#      - name: Run Ui Tests
#        run: |
#          xcodebuild test \
#          -scheme SwiftRadioUITests \
#          -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
#          -resultBundlePath ./TestResults.xcresult | xcpretty
#
#          mkdir allure-results
#          xcresults export TestResults.xcresult -o allure-results
#          mkdir allure-report
#          allure generate allure-results --report-dir allure-report
#
#      - name: Load test report history
#        uses: actions/checkout@v3
#        if: always()
#        continue-on-error: true
#        with:
#          ref: gh-pages
#          path: gh-pages
#
#      - name: Build test report
#        uses: simple-elf/allure-report-action@v1.7
#        if: always()
#        with:
#          gh_pages: gh-pages
#          allure_history: allure-history
#          allure_results: allure-results
#
#      - name: Publish test report
#        uses: peaceiris/actions-gh-pages@v3
#        if: always()
#        with:
#          github_token: ${{ secrets.TOKEN }}
#          publish_branch: gh-pages
#          publish_dir: allure-history